### ISSUE TITLE
Discrepancy between `parse_ctl` and `read_ctl`

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/nmrec#13]
Im not sure if this is a bug or desired behavior. Before I describe the problem, here is some context:

 - I am working on creating a bunch of fake control stream files for the purpose of testing various cases of model parameter inheritance. 
 - We dont need each example to be a full control steam: just the required records for `nmrec` to be able to create a `nmrec_ctl_records` object.
 - Seth asked that we avoid touching the disc if possible, so I was initially not using `read_ctl` or `write_ctl`

Here is the behavior:

```r
# Create fake ctl
 .prob <- "base case"
 .block <- "$THETA\n(0, 2)  ; KA\n(0, 3)  ; CL\n(0, 10) ; V2\n(0.02)  ; RUVp\n(1)     ; RUVa"
template_lines <- glue::glue("$PROBLEM {.prob}\n\n{.block}") %>%
    as.character()
ctl <- nmrec::parse_ctl(template_lines)

# Try to inspect theta record afterwards (doesnt work)
> nmrec::select_records(ctl, "theta")
list()

# when saving out the file first
temp_ctl_path <- tempfile(pattern = "temp-ctl-", fileext = ".ctl")
nmrec::write_ctl(ctl, temp_ctl_path)
ctl_gen <- nmrec::read_ctl(temp_ctl_path)

# Try to inspect theta record afterwards (works)
> nmrec::select_records(ctl_gen, "theta")
[[1]]
$THETA
(0, 2)  ; KA
(0, 3)  ; CL
(0, 10) ; V2
(0.02)  ; RUVp
(1)     ; RUVa
```

**Comment by kyleam** [comment]
`parse_ctl` takes lines of the control stream, not a scalar with the entire content.  We can update it to abort if the user passes something with a new line, but, at a glance, yes, it's working as intended/documented; you're providing invalid input.

**Comment by kyleam** [comment]
> Discrepancy between parse_ctl and read_ctl

read_ctl is just a light wrapper for parse_ctl, so it's not a discrepancy in the behavior:

https://github.com/metrumresearchgroup/nmrec/blob/37a3acb2837bf03e01f098979053a7a22c4ae51e/R/read-ctl.R#L32-L34

**Comment by barrettk** [comment]
> read_ctl is just a light wrapper for parse_ctl, so it's not a discrepancy in the behavior:

Yeah I had taken a look at that and was initially even more confused, but I just realized I missed the idea that `readLines` returns a vector instead of a single string.

Fixed:
```r
>   template_lines <- glue::glue("$PROBLEM {.prob}\n\n{.block}") %>%
+     as.character() %>% strsplit("\n") %>% unlist()
>   ctl <- nmrec::parse_ctl(template_lines)
> ctl
$PROBLEM base case

$THETA
(0, 2)  ; KA
(0, 3)  ; CL
(0, 10) ; V2
(0.02)  ; RUVp
(1)     ; RUVa
> nmrec::select_records(ctl, "theta")
[[1]]
$THETA
(0, 2)  ; KA
(0, 3)  ; CL
(0, 10) ; V2
(0.02)  ; RUVp
(1)     ; RUVa
```

**Comment by barrettk** [comment]
> parse_ctl takes lines of the control stream, not a scalar with the entire content. We can update it to abort if the user passes something with a new line, but, at a glance, yes, it's working as intended/documented; you're providing invalid input.

I am not opposed to that. The docs do say "lines" rather than a string, so up to you if you think that's necessary
