### ISSUE TITLE
get_record_option doesnt work for at least some nested options

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/nmrec#35]
To preface, im not sure if `get_record_option` was intended for records outside of `$EST` blocks, though the documentation doesnt indicate that's the case.

#### Starting records (1001.ctl that's been modified)
In this case, we see two different types of matrix-type records. Diagonal matrices store `standard` as a nested option, but block matrices do not.
```r
> recs
[[1]]
$OMEGA
0.09 STANDARD       ;[P] KOUThealthy

[[2]]
$OMEGA BLOCK (3)
    0.09 STANDARD         ;[P] KOUTdmd
    0.01 COR         ;[P] cov21
    0.09          ;[P] KINdmd
    0.01          ;[P] cov31
    0.01          ;[P] cov32
    0.09          ;[P] SCALAR
```

#### Extracting record options
If I try to extract 'standard' and 'correlation' from the second type, it works as expected:
```r
> c(
+     nmrec::get_record_option(recs[[2]], "standard"),
+     nmrec::get_record_option(recs[[2]], "correlation")
+ )
[[1]]
STANDARD

[[2]]
COR
```

However, for the first record, it doesn't find it:
```r
> nmrec::get_record_option(recs[[1]], "standard")
NULL
```

Is this behavior desired, or can we support nested options as well?

**Comment by barrettk** [comment]
FWIW I wasn't initially planning on using `get_record_option`, and was using logic like this (I know it's flawed/doesnt quite work for all cases). This is also a cropped snipped and doesnt include all the logic:

```r
is_flag_opt <- function(opt){
  (inherits(opt, "nmrec_option_flag") && !inherits(opt, "nmrec_option_record_name")) ||
    (inherits(opt, "nmrec_option_nested") && !inherits(opt, "nmrec_option_pos"))
}

extract_mat_types <- function(ctl, type = c("omega", "sigma")){
  type <- match.arg(type)
  recs <- nmrec::select_records(ctl, type)
  
  purrr::imap_dfr(recs, function(rec, rec_num){
    rec$parse()
    rec_flags <- purrr::keep(rec$values, function(opts){
      is_flag_opt(opts)
    })
    
    rec_flag_names <- purrr::map_chr(rec_flags, function(rec_flag){
      # Handling for nested options (diagonal matrix-type records)
      if(inherits(rec_flag, "nmrec_option_nested")){
        rec_flags_nest <- purrr::keep(rec_flag$values, function(opts_nested){
          is_flag_opt(opts_nested)
        })
        purrr::map_chr(rec_flags_nest, function(rec_flag_nest){
          rec_flag_nest$name
        })
      }else{
        rec_flag$name
      }
    })
  })
}
```

I then thought to reach for `get_record_option`, but ran into similar issues, in that nested options required some extra handling

**Comment by barrettk** [comment]
Sounds good. Im thinking I can extract the matrix type (block vs diagonal), and then use `get_record_option` for block matrices vs a helper I write for diagonal matrices (nested options).

A) Does that logic sound appropriate to you, in terms of being able to rely on `get_record_option` for block matrices? 
B) Do you think it could be worth adding some context about it being for 'simple cases' to the helper doc at some point (obviously low priority though)?

Regardless of those two answers, feel free to close the issue.

**Comment by kyleam** [comment]
> Do you think it could be worth adding some context about it being for 'simple cases' to the helper doc at some point (obviously low priority though)?

Sure, doc improvements are always welcome.  In this case, it'd need more thought than my quick reply.  I don't think I'd say "simple cases" in the docs because I'm not sure it's really that.  As far as I know, it has full support for returning all of a *record's* option (with the documented caveat for the name "option"); it's just not going to recurse into every nested option and return *their* options.  So, I think it should probably be framed in that way.

(Sorry, I know you asked something else, but I won't get to looking at that until later.)

**Comment by barrettk** [comment]
FWIW here is what I currently have. Doesnt look too pretty, but I think it's better than relying on `get_record_option`. The internal `get_flag_opts()` function will pull all flags out, which I think is better than needing to hard code which option you're looking for. 

<details closed>
<summary>Functions</summary>

```r
get_matrix_opts <- function(.mod){

  check_model_object(.mod, "bbi_nonmem_model")
  ctl <- nmrec::read_ctl(get_model_path(.mod))

  # Function to grab flags
  get_flag_opts <- function(rec){
    purrr::keep(rec$values, function(opt){
      inherits(opt, "nmrec_option_flag") &&
        !inherits(opt, "nmrec_option_record_name")
    })
  }

  # Handling for nested options (diagonal matrix-type records)
  get_nested <- function(rec){
    purrr::keep(rec$values, function(opt){
      inherits(opt, "nmrec_option_nested")
    })
  }

  extract_mat_opts <- function(ctl, type = c("omega", "sigma")){
    type <- match.arg(type)
    recs <- nmrec::select_records(ctl, type)
    mat_types <- get_matrix_types(recs)

    purrr::imap_dfr(recs, function(rec, rec_num){
      mat_type <- mat_types[rec_num]
      if(mat_type == "block"){
        rec_flags <- get_flag_opts(rec)
      }else if(mat_type == "diagonal"){
        rec$parse()
        nested_recs <- get_nested(rec)
        rec_flags <- unlist(purrr::map(nested_recs, get_flag_opts))
      }

      rec_flag_names <- purrr::map_chr(rec_flags, function(rec_flag){
        rec_flag$name
      })

      # If no flags found, return defaults
      if(length(rec_flag_names) == 0){
        mat_opts <- c("diag" = "variance", "off_diag" = "covariance")
      }else{
        # Handle diagonal
        if(any(str_detect(rec_flag_names, "standard"))){
          mat_opts <- c("diag" = "standard")
        }else{
          mat_opts <- c("diag" = "variance")
        }

        # Handle off-diagonal
        if(any(str_detect(rec_flag_names, "correlation"))){
          mat_opts <- c(mat_opts, "off_diag" = "correlation")
        }else{
          mat_opts <- c(mat_opts, "off_diag" = "covariance")
        }
      }

      c(record_type = type, mat_type = mat_type, record_number = rec_num, mat_opts)
    })
  }

  bind_rows(
    extract_mat_opts(ctl, "omega"),
    extract_mat_opts(ctl, "sigma")
  )
}


#' Get matrix type for omega and sigma records
#'
#' @param records character vector or list of vectors containing the lines of
#'   the control stream file. Must contain a block header (e.g. $OMEGA)
#'
#' @keywords internal
get_matrix_types <- function(records){
  if(!inherits(records, "list")) records <- list(records)

  purrr::map_chr(records, function(rec){
    rec$parse()
    rec_label <- purrr::keep(rec$values, function(rec_opt){
      inherits(rec_opt, "nmrec_option_value")
    })

    if(rlang::is_empty(rec_label)){
      return("diagonal")
    }else{
      rec_label[[1]]$name
    }
  })
}
```
</details>

#### Relevant records (only omega shown)
```r
> recs
[[1]]
$OMEGA
0.09 STANDARD       ;[P] KOUThealthy

[[2]]
$OMEGA BLOCK (3)
    0.09 STANDARD         ;[P] KOUTdmd
    0.01 COR         ;[P] cov21
    0.09          ;[P] KINdmd
    0.01          ;[P] cov31
    0.01          ;[P] cov32
    0.09          ;[P] SCALAR
```

#### Output
```r
> get_matrix_opts(.mod)
# A tibble: 3 × 5
  record_type mat_type record_number diag     off_diag   
  <chr>       <chr>    <chr>         <chr>    <chr>      
1 omega       diagonal 1             standard covariance 
2 omega       block    2             standard correlation
3 sigma       diagonal 1             variance covariance 
```

Note that I still haven't looked into `CHOLESKY`, but Im punting that to later

**Comment by kyleam** [comment]
> Sounds good. Im thinking I can extract the matrix type (block vs diagonal), and then use `get_record_option` for block matrices vs a helper I write for diagonal matrices (nested options).
>
> A) Does that logic sound appropriate to you, in terms of being able to rely on `get_record_option` for block matrices?

Yes, my understanding is that NONMEM applies any options for a `BLOCK` apply to every initial estimate value.  nmrec should parse all of these at the *record* level, so `get_record_option` should work if you want to use it.  If I were writing it, I'd probably avoid it (and based on your next message is sounds like you are) because you don't need its name resolution.

**Comment by kyleam** [comment]
Doc issue opened at: gh-36

That covers what's actionable at the moment from nmrec's side, but please feel free to continue commenting here.
