### ISSUE TITLE
Allow for multiple options in $DATA 

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/nmrec#39]
It's common to write multiple `IGNORE` statements in `$DATA`, multiple options are not allowed. I'm not sure `nmrec` has features for parsing all of this at this time, but multiple options could be considered for future expansion. 

``` r
library(nmrec)

ctl <- '
$PROBLEM multiple ignore

$DATA foo.csv IGNORE = "C"
IGNORE=(BLQ.EQ.1) 
IGNORE(AGE.GT.100)

$PK
TVCL = THETA(1)
'
file <- tempfile()
writeLines(text = ctl, con = file)

ctl <- nmrec::parse_ctl(readLines(file))
data <- nmrec::select_records(ctl, "data")
ig <- nmrec::get_record_option(data[[1]], "ignore")
#> Error in `nmrec::get_record_option()`:
#> ! Record has more than one ignore option
#> • IGNORE = "C"
#> • IGNORE=(BLQ.EQ.1)
#> • IGNORE(AGE.GT.100)
```

<sup>Created on 2024-05-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by kyleam** [comment]
> It's common to write multiple `IGNORE` statements in `$DATA`, multiple options are not allowed. I'm not sure `nmrec` has features for parsing all of this at this time

`get_record_option()` is a convenience helper for getting a unique option, but all of the `IGNORE` options are parsed and available:

``` r
library(nmrec)

ctl <- nmrec::parse_ctl(
  c(
    "$PROBLEM multiple ignore",
    '$DATA foo.csv IGNORE = "C"',
    "IGNORE=(BLQ.EQ.1)",
    "IGNORE(AGE.GT.100)"
  )
)
data <- nmrec::select_records(ctl, "data")[[1]]
igs <- purrr::keep(
  data$get_options(),
  function(o) identical(o[["name"]], "ignore")
)
igs
#> [[1]]
#> IGNORE = "C"
#> 
#> [[2]]
#> IGNORE=(BLQ.EQ.1)
#> 
#> [[3]]
#> IGNORE(AGE.GT.100)
igs[[2]]$name_raw
#> [1] "IGNORE"
igs[[2]]$value
#> [1] "(BLQ.EQ.1)"

igs[[2]]$value <- "bar"
data
#> $DATA foo.csv IGNORE = "C"
#> IGNORE=bar
#> IGNORE(AGE.GT.100)
```

**Comment by kylebaron** [comment]
Thanks, @kyleam; didn't realize there was another path for this. Looking for a way to drop `IGNORE(BLQ.EQ.1)` ... might still be possible with this route.

**Comment by kyleam** [comment]
> Looking for a way to drop `IGNORE(BLQ.EQ.1)`

One option is to set the value to `NULL`:

``` r
library(nmrec)

ctl <- nmrec::parse_ctl(
  c(
    "$PROBLEM multiple ignore",
    '$DATA foo.csv IGNORE = "C"',
    "IGNORE=(BLQ.EQ.1)",
    "IGNORE(AGE.GT.100)"
  )
)
data <- nmrec::select_records(ctl, "data")[[1]]
for (o in data$get_options()) {
  if (identical(o$value, "(BLQ.EQ.1)")) {
    o$value <- NULL
  }
}
data
#> $DATA foo.csv IGNORE = "C"
#> 
#> IGNORE(AGE.GT.100)
```

I think the main thing that would need thought there is what the "is BLQ.EQ.1?" condition looks like.  It'd certainly be something other than that `identical` condition (likely a regex) given the flexibility in how that can be specified.  nmrec doesn't parse *within* the value, and it considers the parentheses as part of the value.

**Comment by kyleam** [comment]
Also: if you need more fine-grained control (e.g., you want to clean up that empty line), you can work directly with the `data$values` list, which contains a mix of `nmrec_elements` object (things like new lines) and `nmrec_options`.
